name: every-rss-feed

services:
  postgres:
    image: postgres
    container_name: every-rss-feed-postgres
    environment:
      POSTGRES_DB: every-rss-feed
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - every-rss-feed_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: every-rss-feed-redis
    ports:
      - "6379:6379"
    volumes:
      - every-rss-feed_redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  every-rss-feed_postgres_data:
  every-rss-feed_redis_data:
